import { Injectable } from '@angular/core';

import { DataSnapshot } from '@angular/fire/database/interfaces';
import { Hero } from './hero';
import { Subject } from 'rxjs';

import * as firebase from 'firebase/app';
import 'firebase/database';

@Injectable({
  providedIn: 'root'
})
export class HeroService {

  heroes: Hero[] = [];
  heroesSubject = new Subject<Hero[]>();

  constructor(){
    //this.getHeroes();
  }

  emitHeroes(){   
    this.heroesSubject.next(this.heroes);
  }

  /**
  * Set to the firebase realtime database a hero (new, edited or deleted)
  * @uid the Hero idUser (generated by firebase connection application)
  */
  saveHeroes(uid: string){ 
    firebase.database().ref('hero/'+uid).set(this.heroes);
  }

  /**
  * Get the firebase realtime database hero list
  */
  getHeroes(){    // Récupère une liste de héros
    firebase.database().ref('/hero/').on('value', (data: DataSnapshot) => {
      this.heroes = data.val() ? data.val() : []; 
      this.emitHeroes();
    })
  }

  /**
  * Get the firebase realtime database hero corresponding to @uid
  * @uid the Hero idUser 
  * Returns a promise containing or an error or a Hero
  */
  getSingleHero(uid: string){    // récupère un héro par son id
    return new Promise(
        (resolve, reject) => {
          firebase.database().ref('/hero/'+uid+'/0').once('value').then((data:DataSnapshot)=> {
                  //console.log(data.val());
                  resolve(data.val());
              }, (error) =>{
                  console.log(error.code);
                  console.log(error.message);
                  reject(error);
              }
          );
        }
    );
  }

  /**
  * Creates and save to local var new Hero attributes, then save it on database
  * @newHero all of the new hero data (Hero obj)
  * @uid the currently connected user. Will be the Hero idUser 
  */
  createNewHero(newHero: Hero, uid: string){
    // console.log(this.heroes)
    // this.heroes = [newHero, ...this.heroes];
    this.heroes = []; 
    this.heroes.unshift(newHero);
    this.heroes.splice(1, (this.heroes.length-1));
    this.saveHeroes(uid);
    this.emitHeroes();
  }

  /**
  * Updates and save to local var Hero attributes, then save those changes on database
  * @hero all of the edited hero data (Hero obj)
  * @uid the currently connected user. Will be the Hero idUser 
  */
  updateHero(hero: Hero, uid: string){
    this.heroes = []; 
    this.heroes.unshift(hero)
    this.heroes.splice(1, this.heroes.length-1);
    this.saveHeroes(uid);
    this.emitHeroes(); 
  }

  /**
  * Deletes this hero data then save those changes on database
  * @hero all of the deleted hero data (Hero obj)
  */
  removeHero(hero: Hero){
    this.heroes[hero.idUser] = null ;
    this.saveHeroes('');
    this.emitHeroes();
  }
  
}
