import { Hero } from '../../heroes/shared/hero'

export class Account {
    idUser: string;
    displayName: string;
    email: string;
    role: string = 'user' ;
    creationDate: string;
    hero: Hero

    /**
     * Creates a new instance of Account and sets some datas :
     * @email the email used to log in
     * @userId the id generated by firebase when creating account
     * @createDate the the creation date of this account
     */
    constructor(email: string, userId: string, createDate: string){
        this.idUser = userId;
        this.email = email;
        this.creationDate = createDate;
    }

    /**
     * Adds a relationship between the user and its hero
     * @hero the hero owned by the user
     */
    addHero(hero: Hero){
        this.hero = hero ;
    }
}
